name: Deploy Downgrade Subscriptions WebJob

on:
  workflow_dispatch:

  push:
    branches: [ master ]

env:
  WEBJOB_NAME: DowngradeSubscriptionJob
  AZURE_APP_NAME: ApollosLibraryCom
  AZURE_WEBAPP_PACKAGE_PATH: ApollosLibrary.DowngradeSubscriptionJob/publish
  WORKING_DIRECTORY: ApollosLibrary.DowngradeSubscriptionJob
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.APOLLOS_LIBRARY_WEBJOB }}
  CONFIGURATION: Release
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v2

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: dotnet restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    
    - name: dotnet build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o './publish/App_Data/Jobs/Continuous/${{ env.WEBJOB_NAME }}' ${{ env.WORKING_DIRECTORY }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: env.AZURE_WEBAPP_PACKAGE_PATH