name: Build and deploy .NET Core app to Linux WebApp ApollosLibraryWebAPI
on:
  push:
    branches:
    - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build, Push and Release a Docker container to Heroku.
      uses: gonuit/heroku-docker-deploy@v1.3.3

