name: Build and deploy .NET Core app to Linux WebApp ApollosLibraryWebAPI
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: ApollosLibraryWebAPI
  AZURE_WEBAPP_PACKAGE_PATH: ApollosLibrary.WebApi/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.ApollosLibraryWebAPI_d5ab }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: ApollosLibrary.WebApi
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Azure Container Registry Build
      uses: Azure/acr-build@v1
      with:
        dockerfile: ./Dockerfile
      
